### ISSUE TITLE
Modify the texture of plants

### ISSUE THREAD

**Issue by Pailomot** [GrassyDev/PvZCubed#10]
I think it's great how the textures are, but I feel them somewhat weird some like the nutt and also that they have too many blocks the models making that in many quantities of a plant can cause bad optimization
If you want me to help you in what I told you my discord: Pailomot#5814

**Comment by GrassyDev** [comment]
The latest update has improved textures for the Peashooter, Repeater, and Threepeater. I will try to improve the textures of other plants in the incoming updates.

**Comment by GrassyDev** [comment]
As of the latest Early Access versions, every plant and zombie have their textures improved
