### ISSUE TITLE
Prevent the spawning of Graves on the first few days to allow players to prepare for Zombies

### ISSUE THREAD

**Issue by cannon9009** [GrassyDev/PvZCubed#21]
Suggestion's in the title. It's a little annoying to immediately start a world with Graves spawning when you don't even have wooden tools created yet, let alone a home, considering Zombies seem to have defense and cannot be simply whacked away with your fists (hitting with Fists shows no health loss particles). Preferrably, it should be:
- 3-4 days on Easy
- 2-3 days on Normal
- 1-2 days on Hard
- No grace period on Hardcore

If not making it mandatory, at least make it an option in the config for those who wish to enable it. Optionally make a sound play when Grave spawning is enabled after the grace period ends. Also optionally, you can limit what plant types spawn during the grace period (or just planting them in general, which would remove Sun generation without Solar Winds or random Peashooters), to prevent farming powerful plants easily due to the threat of Zombies missing for the first few days.

**Comment by cannon9009** [comment]
Also as a side suggestion, please give the option to change grave spawn rates, I can't kill these zombies faster than the graves spawn...

**Comment by GrassyDev** [comment]
The current grace period is 5 minutes, but I could add options to extend it
And if you go to the configs in the latest update, you will see that you can change their spawn rates, you just have to lower the value in the grave's weight so that they spawn less often

**Comment by cannon9009** [comment]
> And if you go to the configs in the latest update, you will see that you can change their spawn rates, you just have to lower the value in the grave's weight so that they spawn less often

Alright, thank you for pointing that out. How often do they spawn in the default "10" weight?

**Comment by cannon9009** [comment]
I just checked the configs for Grave spawning and it seems that configs in the modmenu don't accept decimals. Not really sure if it's just a Mod Menu thing or if it's exclusive to this mod but I thought I'd go ahead and say that here.
